In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/netflix-shows-and-movies/Cleaned_Netflix_Data.csv
/kaggle/input/tv-shows-on-ott-platforms/TV_Shows.csv

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [4]:
data = pd.read_csv('/kaggle/input/netflix-shows-and-movies/Cleaned_Netflix_Data.csv')
data

,Id,Title,Type,Release_Year,Age_Certification,Genres,Production_Countries,IMDB_Score,IMDB_Popularity
0,tm84618,Taxi Driver,MOVIE,1976,R,Drama,US,8.2,40.965
1,tm154986,Deliverance,MOVIE,1972,R,Drama,US,7.7,10.010
2,tm127384,MontyPythonandtheHolyGrail,MOVIE,1975,PG,Fantasy,GB,8.2,15.461
3,tm120801,TheDirtyDozen,MOVIE,1967,NaN,War,GB,7.7,20.398
4,ts22164,MontyPython'sFlyingCircus,SHOW,1969,TV-14,Comedy,GB,8.8,17.617
...,...,...,...,...,...,...,...,...,...
5844,tm1014599,FineWine,MOVIE,2021,NaN,Romance,NG,6.8,1.466
5845,tm898842,C/OKaadhal,MOVIE,2021,NaN,Drama,NaN,7.7,NaN
5846,tm1059008,Lokillo,MOVIE,2021,NaN,Comedy,CO,3.8,26.005
5847,tm1035612,DadStopEmbarrassingMe-TheAfterparty,MOVIE,2021,PG-13,NaN,US,NaN,1.296
5848,ts271048,MightyLittleBheem:KiteFestival,SHOW,2021,NaN,Family,NaN,7.8,2.289

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5849 entries, 0 to 5848
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Id                    5849 non-null   object
 1   Title                 5848 non-null   object
 2   Type                  5849 non-null   object
 3   Release_Year          5849 non-null   int64
 4   Age_Certification     3230 non-null   object
 5   Genres                5790 non-null   object
 6   Production_Countries  5619 non-null   object
 7   IMDB_Score            5368 non-null   float64
 8   IMDB_Popularity       5758 non-null   float64
dtypes: float64(2), int64(1), object(6)
memory usage: 411.4+ KB

In [6]:
data = data.sort_values(by = "Release_Year")
data

,Id,Title,Type,Release_Year,Age_Certification,Genres,Production_Countries,IMDB_Score,IMDB_Popularity
12,tm16479,WhiteChristmas,MOVIE,1954,NaN,Romance,US,7.5,8.915
21,tm19608,TheBlazingSun,MOVIE,1954,NaN,Crime,EG,7.4,2.184
22,tm204541,DarkWaters,MOVIE,1956,NaN,Action,EG,6.7,0.849
13,tm135083,CairoStation,MOVIE,1958,NaN,Drama,EG,7.5,5.546
30,tm358653,Ujala,MOVIE,1959,NaN,Romance,IN,6.6,0.840
...,...,...,...,...,...,...,...,...,...
5558,tm1196455,ThePhotographer:MurderinPinamar,MOVIE,2022,NaN,Documentation,AR,6.7,49.939
5305,tm1185506,TheTamingoftheShrewd,MOVIE,2022,NaN,Romance,PL,4.5,9.926
4931,ts330347,CracowMonsters,SHOW,2022,TV-MA,Scifi,PL,5.5,119.993
4923,tm1180610,TheWrathofGod,MOVIE,2022,NaN,Thriller,AR,5.7,445.767
4887,ts301625,HoldTight,SHOW,2022,TV-MA,Crime,PL,6.1,6.901

In [7]:
data.isna().sum()

Id                         0
Title                      1
Type                       0
Release_Year               0
Age_Certification       2619
Genres                    59
Production_Countries     230
IMDB_Score               481
IMDB_Popularity           91
dtype: int64

In [8]:
data = data.drop("Age_Certification", axis=1)
data

,Id,Title,Type,Release_Year,Genres,Production_Countries,IMDB_Score,IMDB_Popularity
12,tm16479,WhiteChristmas,MOVIE,1954,Romance,US,7.5,8.915
21,tm19608,TheBlazingSun,MOVIE,1954,Crime,EG,7.4,2.184
22,tm204541,DarkWaters,MOVIE,1956,Action,EG,6.7,0.849
13,tm135083,CairoStation,MOVIE,1958,Drama,EG,7.5,5.546
30,tm358653,Ujala,MOVIE,1959,Romance,IN,6.6,0.840
...,...,...,...,...,...,...,...,...
5558,tm1196455,ThePhotographer:MurderinPinamar,MOVIE,2022,Documentation,AR,6.7,49.939
5305,tm1185506,TheTamingoftheShrewd,MOVIE,2022,Romance,PL,4.5,9.926
4931,ts330347,CracowMonsters,SHOW,2022,Scifi,PL,5.5,119.993
4923,tm1180610,TheWrathofGod,MOVIE,2022,Thriller,AR,5.7,445.767
4887,ts301625,HoldTight,SHOW,2022,Crime,PL,6.1,6.901

In [9]:
data.isna().sum()

Id                        0
Title                     1
Type                      0
Release_Year              0
Genres                   59
Production_Countries    230
IMDB_Score              481
IMDB_Popularity          91
dtype: int64

In [14]:
data.Genres.fillna("Genre Unavailable", inplace=True)
data.Production_Countries.fillna("Country Unavailable", inplace=True)
data.isna().sum()

Id                        0
Title                     1
Type                      0
Release_Year              0
Genres                    0
Production_Countries      0
IMDB_Score              481
IMDB_Popularity          91
dtype: int64

In [20]:
data['IMDB_Score'].fillna(data['IMDB_Score'].mode()[0], inplace=True)
data['IMDB_Popularity'].fillna(data['IMDB_Popularity'].mode()[0], inplace=True)
data.dropna(subset=['Title'], inplace=True)
data.isna().sum()

Id                      0
Title                   0
Type                    0
Release_Year            0
Genres                  0
Production_Countries    0
IMDB_Score              0
IMDB_Popularity         0
dtype: int64

In [17]:
data

,Id,Title,Type,Release_Year,Genres,Production_Countries,IMDB_Score,IMDB_Popularity
12,tm16479,WhiteChristmas,MOVIE,1954,Romance,US,7.5,8.915
21,tm19608,TheBlazingSun,MOVIE,1954,Crime,EG,7.4,2.184
22,tm204541,DarkWaters,MOVIE,1956,Action,EG,6.7,0.849
13,tm135083,CairoStation,MOVIE,1958,Drama,EG,7.5,5.546
30,tm358653,Ujala,MOVIE,1959,Romance,IN,6.6,0.840
...,...,...,...,...,...,...,...,...
5558,tm1196455,ThePhotographer:MurderinPinamar,MOVIE,2022,Documentation,AR,6.7,49.939
5305,tm1185506,TheTamingoftheShrewd,MOVIE,2022,Romance,PL,4.5,9.926
4931,ts330347,CracowMonsters,SHOW,2022,Scifi,PL,5.5,119.993
4923,tm1180610,TheWrathofGod,MOVIE,2022,Thriller,AR,5.7,445.767
4887,ts301625,HoldTight,SHOW,2022,Crime,PL,6.1,6.901

In [21]:
data.to_csv('Netflix_data_cleaned.csv', index=False)